// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppIconService lets the frontend list, read, and change the desktop app's Dock icon.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetAppIcon returns the currently selected icon name.
 */
export function GetAppIcon(): $CancellablePromise<string> {
    return $Call.ByID(1981410773);
}

/**
 * GetAppIconOptions returns the available icon names, in display order.
 */
export function GetAppIconOptions(): $CancellablePromise<string[]> {
    return $Call.ByID(1157650581).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetAppIcon changes the Dock icon and persists the choice for future launches.
 */
export function SetAppIcon(name: string): $CancellablePromise<void> {
    return $Call.ByID(2012694353, name);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
